# Generated by Django 4.2.4 on 2023-08-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0006_alter_about_user_alter_contact_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(
                choices=[
                    ("Bac+2", "Bac+2"),
                    ("Bac+3/Licence", "Bac+3/Licence"),
                    ("bachelor", "Bachelor"),
                    ("master", "Master"),
                    ("phd", "PhD"),
                ],
                max_length=100,
                null=True,
                verbose_name="Degree",
            ),
        ),
    ]
