# Generated by Django 4.2.4 on 2023-08-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0008_alter_education_degree"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/", verbose_name="Image")),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.AddField(
            model_name="project",
            name="images",
            field=models.ManyToManyField(
                blank=True, to="Home.image", verbose_name="Project Images"
            ),
        ),
    ]
