# Generated by Django 4.2.4 on 2023-08-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0017_alter_profile_image_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="title",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Skill Title"
            ),
        ),
    ]
