# Generated by Django 4.2.4 on 2023-08-27 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Home", "0018_alter_skill_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="percent",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Enter a value between 0 and 100",
                null=True,
                verbose_name="Proficiency Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("expert", "Expert"),
                ],
                default="beginner",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Skill Title"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="user",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Skills",
        ),
    ]
