# Generated by Django 4.2.4 on 2023-08-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0021_alter_skill_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="percent",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="proficiency",
        ),
        migrations.AlterField(
            model_name="skill",
            name="title",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Skill Title"
            ),
        ),
        migrations.CreateModel(
            name="SkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Skill Tag"
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.skill"
                    ),
                ),
            ],
        ),
    ]
