# Generated by Django 4.2.4 on 2023-08-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0023_skill_percent_skill_proficiency_alter_skill_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Description"
            ),
        ),
    ]
