# Generated by Django 4.2.4 on 2023-08-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0024_profile_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="introduction",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Introduction"
            ),
        ),
    ]
