# Generated by Django 4.2.4 on 2023-08-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0025_skill_introduction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="introduction",
        ),
        migrations.AddField(
            model_name="about",
            name="introduction",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Introduction skills",
            ),
        ),
    ]
