# Generated by Django 4.2.4 on 2023-08-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0026_remove_skill_introduction_about_introduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="sumary",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Sumary"
            ),
        ),
    ]
