# Generated by Django 4.2.4 on 2023-08-28 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0028_category_project_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="primary_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_for",
                to="Home.projectimage",
            ),
        ),
    ]
