# Generated by Django 4.2.4 on 2023-08-28 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0029_project_primary_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="primary_image",
        ),
    ]
