# Generated by Django 4.2.4 on 2023-08-28 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0030_remove_project_primary_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectimage",
            name="project",
        ),
        migrations.AddField(
            model_name="project",
            name="primary_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_for",
                to="Home.projectimage",
            ),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="title",
            field=models.CharField(
                choices=[("primary", "primary"), ("secondary", "secondary")],
                default="secondary",
                max_length=100,
                null=True,
                verbose_name="Image Title",
            ),
        ),
    ]
