# Generated by Django 4.2.4 on 2023-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0032_projectimage_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimage",
            name="project_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Project Name"
            ),
        ),
    ]
