# Generated by Django 4.2.4 on 2023-08-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0034_remove_projectimage_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="project",
            field=models.ForeignKey(
                choices=[("primary", "Primary"), ("secondary", "Secondary")],
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="Home.project",
            ),
        ),
    ]
