# Generated by Django 4.2.4 on 2023-08-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0036_alter_projectimage_project_alter_projectimage_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="title",
            field=models.CharField(
                choices=[("primary", "Primary"), ("secondary", "Secondary")],
                default="secondary",
                max_length=100,
                null=True,
                verbose_name="Image Title",
            ),
        ),
    ]
